server:
  port: 9000

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./data/test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true